### ISSUE TITLE
Scrolling Not Working

### ISSUE THREAD

**Issue by johnellison** [Yappli/smooth-scroll#7]
I'm not sure if I'm missing something here, but I've installed smooth-scroll via `bower install` and have used gulp wiredep to inject the script into my layout file.

Both locally and in production the smooth scrolling doesn't work. I'm not a javascript guy but there aren't any errors in the console, it just doesn't smooth scroll...

Production: http://www.john-ellison.com/
Development: https://github.com/johnellison/john-ellison.com

**Comment by Yappli** [comment]
Hi @johnellison,

I didn't find any trace of smooth-scroll in your website http://www.john-ellison.com. I recommend you to generate two version of your javascript files : one minified and one not minified (only concatenate) to read it back easily.

Let me know if you found the bug.

**Comment by johnellison** [comment]
smooth-scroll.js was in my vendor.js file. The bug was that I had my anchor links prefixed with `/`. I updated them as `#first-link`, `#second-link` and so on and it worked.
